name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: install
      run: 
        sh install_ubuntu.sh
    
    - name: chmod
      run:
        chmod -R 777 binshell

    - name: make release
      run:
        sh binshell/make_release.sh

    - name: tar
      run:
        tar -czvf skynet_fly-master.tar.gz skynet-fly-release

    - name: Debug List current working directory
      run: ls -alh

    - name: Debug List the release directory
      run: ls -alh skynet_fly-master.tar.gz

    - name: pwd
      run: pwd

    - name: Upload tar as artifact
      uses: actions/upload-artifact@master
      with:
        name: release-artifact
        path: skynet_fly-master.tar.gz  # 上传压缩文件为artifact
        
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
       - name: Download artifact
         uses: actions/download-artifact@master
         with:
          name: release-artifact  # 下载构建时上传的 artifact

       - name: Debug List files in directory after build
         run: ls -alh
           
       - name: pwd
         run: pwd
        
       - name: Debug List the release directory
         run: ls -alh skynet_fly-master.tar.gz
        
       - name: Create GitHub Release
         uses: softprops/action-gh-release@master
         with:
           files: skynet_fly-master.tar.gz
           tag_name: master
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write  # 保证GITHUB_TOKEN有足够的权限
  packages: write