name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: install
      run: 
        sh install_ubuntu.sh
        chmod -R 777 binshell
        sh binshell/make_release.sh
        tar -czvf skynet_fly-master.tar.gz skynet-fly-release

    - name: Debug List current working directory
      run: ls -alh

    - name: Debug List the release directory
      run: ls -alh skynet-fly-release
        
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
       - name: Debug List files in directory after build
         run: |
           ls -alh
        
       - name: Create GitHub Release
         uses: softprops/action-gh-release@master
         with:
           files: skynet_fly-master.tar.gz
           tag_name: master
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
